[info]
name = "data_processor"
version = "0.0.1"
description = ""

[deployment]
type = "PORT"
dest = 4000
scripts = ['make install']
artifact_folder = ""

[config]
aws_access_key = ""
aws_secret_key = ""
mysql_usr = ""
mysql_pwd = ""
mysql_host = ""
mysql_db = ""